name: CD Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x

    - name: Install Dependencies
      working-directory: ./Bengluru_house_price_prediction
      run: npm ci

    - name: Build Frontend
      working-directory: ./Bengluru_house_price_prediction
      run: npm run build

    - name: Deploy to Hosting Service Placeholder
      run: echo 'Deploying application to production (replace with specific deployment CLI e.g. vercel, netlify or scp)'
