name: CI Testing

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: Bengluru_house_price_prediction/package-lock.json

    - name: Install Frontend Dependencies
      working-directory: ./Bengluru_house_price_prediction
      run: npm ci

    - name: Run Frontend Linting
      working-directory: ./Bengluru_house_price_prediction
      run: npm run lint

    - name: Run Frontend Type Check
      working-directory: ./Bengluru_house_price_prediction
      run: npx tsc --noEmit

    - name: Run Frontend Tests
      working-directory: ./Bengluru_house_price_prediction
      run: npm run test
